apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: default
type: Opaque
data:
  DB_HOST: URL(base64 encoded)  
  DB_PORT: 5432
  DB_NAME: appdb
  DB_USER: appuser
  DB_PASSWORD: password(base64 encoded)